 export default [
    {
      key:0,
      detail:"/disney-cl/detail",
      title:"Eternals",
      description:"Marvel Studios’ 'Eternals' follows a group of ancient heroes from beyond the stars who had protected Earth since the dawn of man. When monstrous creatures called Deviants, long thought lost to history, mysteriously return, the Eternals are forced to reunite in order to defend humanity once again.",
      trailer:"https://www.youtube.com/watch?v=x_me3xsvDgk",
      duration:"2h:37m",
      year:"2021",
     director:"Chloé Zhao",
     img:"https://images-na.ssl-images-amazon.com/images/I/81iWs7Ea8ZL._RI_.jpg",
     imgTitle:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/D734418FF951C8DE710A56BBB148DBC507021D3C37BB08D25C035E019541DF6D/scale?width=1440&aspectRatio=1.78&format=png",
    },
    {
      key:1,
      detail:"/disney-cl/detail1",
      title:"Nightmare Alley ",
      description:"In 1940s New York, down-on-his-luck Stanton Carlisle endears himself to a clairvoyant and her mentalist husband at a traveling carnival. Using newly acquired knowledge, Carlisle crafts a golden ticket to success by swindling the elite and wealthy. Hoping for a big score, he soon hatches a scheme to con a dangerous tycoon with help from a mysterious psychologist who might be his most formidable opponent yet.",
      trailer:"https://www.youtube.com/watch?v=Q81Yf46Oj3s",
      duration:"2h:20m",
      year:"2021",
     director:"Guillermo del Toro",
     img:"https://m.media-amazon.com/images/M/MV5BOTI4NDhhNGEtZjQxZC00ZTRmLThmZTctOGJmY2ZlOTc0ZGY0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg",
     imgTitle:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/965879174418BE5E7C64B9C63719B4B696454913873BBF7CED65B581327645EC/scale?width=1440&amp;aspectRatio=1.78&amp;format=png",

    },
    {
      key:2,
      detail:"/disney-cl/detail2",
      title:"Death on the Nile",
      description:"Belgian sleuth Hercule Poirot's Egyptian vacation aboard a glamorous river steamer turns into a terrifying search for a murderer when a picture-perfect couple's idyllic honeymoon is tragically cut short.",
      trailer:"https://www.youtube.com/watch?v=dZRqB0JLizw",
      duration:"2h:07m",
      year:"2022",
     director:"Kenneth Branagh",
     img:"https://m.media-amazon.com/images/M/MV5BNjI4ZTQ1OTYtNTI0Yi00M2EyLThiNjMtMzk1MmZlOWMyMDQwXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg",
     imgTitle:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/9CD7BEFEF5CF779C2502F63C8F992B2B8E48A6E9336C3A6B187861BEBE667CD9/scale?width=1440&amp;aspectRatio=1.78&amp;format=png"
    },
    {
      key:3,
      detail:"/disney-cl/detail3",
      title:"Free Guy ",
      description:"When a bank teller discovers he's actually a background player in an open-world video game, he decides to become the hero of his own story -- one that he can rewrite himself. In a world where there's no limits, he's determined to save the day his way before it's too late, and maybe find a little romance with the coder who conceived him.",
      trailer:"https://www.youtube.com/watch?v=X2m-08cOAbc",
      duration:"1h:55m",
      year:"2021",
     director:" Shawn Levy",
     img:"https://m.media-amazon.com/images/M/MV5BOTY2NzFjODctOWUzMC00MGZhLTlhNjMtM2Y2ODBiNGY1ZWRiXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg",
     imgTitle:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/20EAEA1D499A6D1D4A079D1E0B7453B370711271E9AC40DEEABF4A54D2321D7A/scale?width=1440&amp;aspectRatio=1.78&amp;format=png"
    },
    {
      key:4,
      detail:"/disney-cl/detail4",
      title:"Turning Red",
      description:"Mei Lee is a 13-year-old girl who is torn between being her mother's obedient daughter and the chaos of her youth. As if that were not enough, when she gets too excited, she turns into a big red panda.",
      trailer:"https://www.youtube.com/watch?v=XdKzUbAiswE",
      duration:"1h:40m",
      year:"2022",
     director:"  Domee Shi",
     img:"https://lumiere-a.akamaihd.net/v1/images/c548e282c08cdbcd99ad447adcc0823a_2073x3072_58ed3c57.jpeg",
     imgTitle:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/06CCB07374A8471E15315A085DE06D4B94A7EC8DFB047F16E752EBCF5174379D/scale?width=1440&amp;aspectRatio=1.78&amp;format=png",
    },
    {
      key:5,
      detail:"/disney-cl/detail5",
      title:"The last Duel",
      description:"Jean de Carrouges is a respected knight known for his bravery and skill on the battlefield. Jacques Le Gris is a squire whose intelligence and eloquence makes him one of the most admired nobles in court. When Le Gris viciously assaults Carrouges' wife, she steps forward to accuse her attacker, an act of bravery and defiance that puts her life in jeopardy. The ensuing trial by combat, a grueling duel to the death, places the fate of all three in God's hands.",
      trailer:"https://www.youtube.com/watch?v=oE31KKv0GWU",
      duration:"2h:35m",
      year:"2021",
     director:"   Ridley Scott",
     img:"https://images-na.ssl-images-amazon.com/images/I/919TSF21WAL._RI_.jpg",
     imgTitle:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/52C582C2E432B3D019B455B6A1836C1D785420639A570B09498B81C82A241F10/scale?width=1440&amp;aspectRatio=1.78&amp;format=png",
     
    },
    {
      key:6,
      detail:"/disney-cl/detail6",
      title:"Guardians of the Galaxy Vol. 2",
      description:"After a successful mission, Quill and his team of galactic defenders meet Ego, a man claiming to be Quill's father. However, they soon learn some disturbing truths about Ego.",
      trailer:"https://www.youtube.com/watch?v=dW1BIid8Osg",
      duration:"2h:17m",
      year:"2017",
     director:" James Gunn",
     img:"https://img.reelgood.com/content/movie/e1d3e432-2d92-41cf-9906-bfe916999880/backdrop-1920.jpg",
     imgTitle:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/79CA4539E3423ADDDEA16CEBF6565B244D8EB86E732BD791C75950AB18CA8154/scale?width=1440&amp;aspectRatio=1.78&amp;format=png",
     
    },
    {
      key:7,
      detail:"/disney-cl/detail7",
      title:"Chip 'n Dale: Rescue Rangers",
      description:"Chip and Dale live amongst cartoons and humans in modern-day Los Angeles, but their lives are quite different now. When a former cast mate mysteriously disappears, Chip and Dale must repair their broken friendship and save their friend.",
      trailer:"https://www.youtube.com/watch?v=OIwaY3A7np8",
      duration:"1h:37m",
      year:"2022",
     director:"   Ridley Scott",
     img:"https://m.media-amazon.com/images/M/MV5BZjBlMjIxN2ItNTMyNi00NDk5LWFhMzEtNzdiODE0Y2M4MWI2XkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_.jpg",
     imgTitle:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/0870CB027BB9C4815C7A903013920B528B36B715718B2D5073B166B77CBB4DEB/scale?width=1440&amp;aspectRatio=1.78&amp;format=png",
     
    },


            ]